services:
  db:
    image: postgres:14.15-alpine3.21
    restart: always
    environment:
      POSTGRES_DB: 'films_development'
      POSTGRES_USER: 'films'
      POSTGRES_PASSWORD: 'password'
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
