# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

	# Defining films
	config.vm.define "films" do |films|
		films.vm.box = "ubuntu/precise64"
		films.vm.hostname = "films.mpucholblasco.com"
		films.vm.network "private_network", ip: "10.210.0.10"
		films.vm.provider :virtualbox do |vb|
			vb.customize ["modifyvm", :id, "--memory", "512"]
			vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
			vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
		end

		# Shell provision used to configure puppet version 3.4.2 and install required packages
                #films.vm.provision "shell", path: "shell-provision.sh"
	end
end
